### ISSUE TITLE
Unable to edit the levels on android phone

### ISSUE THREAD

**Issue by browhattheheck1** [vanjac/voxel-editor#341]
I moved the entire assets folder into my project to combine it with my already existing game. I get no errors, but when I move it onto android you cannot edit a world. You can zoom the camera in and out, but you can't click on any walls or floors. Selecting the world button in the drop down doesn't bring up the world ui, it just goes blank. I am unable to test if the selecting problem is happening in the editor as this is made for mobile controls, however hitting the world button in the editor does actually bring up the proper UI. The only difference in my project is that I use LWRP

**Comment by vanjac** [comment]
First step will be trying to get some useful error messages. You actually can test in the editor if you install Unity Remote, it will let you use touch input from your phone to control the editor. Otherwise, you can use the Android Logcat unity package to get log output from your phone.

LWRP is gonna have some issues, especially with skyboxes and shadows. I got halfway through a URP upgrade, you can see my progress on the `urp` branch, but it might take a bit more work.

In general I havent really designed N-Space for integrating with other projects. Not saying its impossible, just that the codebase is a bit tangled and messy.

**Comment by snikabarz** [comment]
Thank you for your response, personally I've never been able to get Unity remote 5 or logcat to ever work (except with a different phone I borrowed from someone else). However, if this is means anything to you, I can move/rotate/edit any object (lights, spheres, and player) but specifically just not the walls/floors/ceiling. When the player touches the wall in the editor it kind of connects to the wall and it will allow me to edit the wall by moving the player, as long as the player touches it. Very strange issue, but could be something more specific to a certain script that you may recognize

**Comment by vanjac** [comment]
You've probably already tried this but just to double check: For logcat and unity remote, you will need to turn on Developer Mode for your phone, and also turn on USB debugging. When your phone is connected you should get a notification saying USB debugging is enabled. Then with your phone plugged in you'll need to go into Project Settings > Editor in unity and switch the Unity Remote device to android. I often have to restart Unity if the remote doesn't work, this usually happens when I disconnect and reconnect my phone.

If you can't get any of that to work, look up how to run logcat from a command prompt using adb. Use the command `adb logcat -s Unity` to filter for messages from the app. Its gonna be really hard to diagnose any problems without error messages.

**Comment by vanjac** [comment]
oh, and I think some phones require USB drivers. I have a Pixel which works without a driver. https://developer.android.com/studio/run/oem-usb
